package types

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/Tencent/WeKnora/internal/textconv"
)

// FAQChunkMetadata defines the structure of an FAQ entry within Chunk.Metadata
type FAQChunkMetadata struct {
	StandardQuestion  string         `json:"standard_question"`
	SimilarQuestions  []string       `json:"similar_questions,omitempty"`
	NegativeQuestions []string       `json:"negative_questions,omitempty"`
	Answers           []string       `json:"answers,omitempty"`
	AnswerStrategy    AnswerStrategy `json:"answer_strategy,omitempty"`
	Version           int            `json:"version,omitempty"`
	Source            string         `json:"source,omitempty"`
}

// GeneratedQuestion represents a single AI-generated question
type GeneratedQuestion struct {
	ID              string `json:"id"`                         // Unique identifier, used to construct source_id
	Question        string `json:"question"`                   // Question content
	ContentRevision *int   `json:"content_revision,omitempty"` // The Chunk content version this question corresponds to
}

const maxGeneratedQuestionSourceIDLength = 64

// GeneratedQuestionSourceID builds the retrieval source identifier for a
// generated question. PostgreSQL stores source_id as varchar(64), while a
// chunk UUID plus a question UUID would be 73 bytes. Preserve the historical
// representation for short IDs and hash only oversized question IDs so
// existing index rows remain addressable by delete/reindex operations.
func GeneratedQuestionSourceID(chunkID, questionID string) string {
	candidate := chunkID + "-" + questionID
	if len(candidate) <= maxGeneratedQuestionSourceIDLength {
		return candidate
	}
	digest := sha256.Sum256([]byte(questionID))
	// UUID chunk IDs use 36 bytes; "-q" plus 24 hex characters keeps the
	// complete identifier at 62 bytes while retaining ample collision space.
	return chunkID + "-q" + hex.EncodeToString(digest[:12])
}

// DocumentChunkMetadata defines the metadata structure for a document Chunk
// Used to store enhancement info such as AI-generated questions
type DocumentChunkMetadata struct {
	// GeneratedQuestions stores questions generated by AI related to this Chunk
	// These questions are indexed independently to improve recall
	GeneratedQuestions []GeneratedQuestion `json:"generated_questions,omitempty"`
	// GeneratedQuestionsRevision ties the questions to Chunk.ContentRevision.
	GeneratedQuestionsRevision int `json:"generated_questions_revision,omitempty"`
}

// IsQuestionCurrent reports whether a generated question was authored for the
// current chunk body. This is advisory metadata for the UI: questions remain
// valid retrieval aliases across chunk edits. Legacy rows fall back to the
// metadata-level revision.
func (m *DocumentChunkMetadata) IsQuestionCurrent(question GeneratedQuestion, chunkRevision int) bool {
	if question.ContentRevision != nil {
		return *question.ContentRevision == chunkRevision
	}
	return m != nil && m.GeneratedQuestionsRevision == chunkRevision
}

// GetQuestionStrings returns a list of question content strings (for backward compatibility with old code)
func (m *DocumentChunkMetadata) GetQuestionStrings() []string {
	if m == nil || len(m.GeneratedQuestions) == 0 {
		return nil
	}
	result := make([]string, len(m.GeneratedQuestions))
	for i, q := range m.GeneratedQuestions {
		result[i] = q.Question
	}
	return result
}

// DocumentMetadata parses document metadata from a Chunk
func (c *Chunk) DocumentMetadata() (*DocumentChunkMetadata, error) {
	if c == nil || len(c.Metadata) == 0 {
		return nil, nil
	}
	var meta DocumentChunkMetadata
	if err := json.Unmarshal(c.Metadata, &meta); err != nil {
		return nil, err
	}
	return &meta, nil
}

// SetDocumentMetadata sets document metadata on a Chunk
func (c *Chunk) SetDocumentMetadata(meta *DocumentChunkMetadata) error {
	if c == nil {
		return nil
	}
	if meta == nil {
		c.Metadata = nil
		return nil
	}
	bytes, err := json.Marshal(meta)
	if err != nil {
		return err
	}
	c.Metadata = JSON(bytes)
	return nil
}

// Sanitize performs basic cleanup on metadata (trims whitespace, deduplicates), preserving the original content
// Used for DB storage, no semantic normalization applied
func (m *FAQChunkMetadata) Sanitize() {
	if m == nil {
		return
	}
	m.StandardQuestion = strings.TrimSpace(m.StandardQuestion)
	m.SimilarQuestions = SanitizeStrings(m.SimilarQuestions)
	m.NegativeQuestions = SanitizeStrings(m.NegativeQuestions)
	m.Answers = SanitizeStrings(m.Answers)
	if m.Version <= 0 {
		m.Version = 1
	}
}

// Normalize returns a normalized copy, used for Hash computation and vector indexing
// The original data is unchanged; a new normalized copy is returned
func (m *FAQChunkMetadata) Normalize() *FAQChunkMetadata {
	if m == nil {
		return nil
	}
	return &FAQChunkMetadata{
		StandardQuestion:  NormalizeQuestion(m.StandardQuestion),
		SimilarQuestions:  normalizeQuestionStrings(m.SimilarQuestions),
		NegativeQuestions: normalizeQuestionStrings(m.NegativeQuestions),
		Answers:           SanitizeStrings(m.Answers), // Answers only get basic cleanup
		AnswerStrategy:    m.AnswerStrategy,
		Version:           m.Version,
		Source:            m.Source,
	}
}

// SanitizeStrings performs basic cleanup on a string list (TrimSpace + deduplication)
func SanitizeStrings(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	dedup := make([]string, 0, len(values))
	seen := make(map[string]struct{}, len(values))
	for _, v := range values {
		trimmed := strings.TrimSpace(v)
		if trimmed == "" {
			continue
		}
		if _, exists := seen[trimmed]; exists {
			continue
		}
		seen[trimmed] = struct{}{}
		dedup = append(dedup, trimmed)
	}
	if len(dedup) == 0 {
		return nil
	}
	return dedup
}

// FAQMetadata parses FAQ metadata from a Chunk
// Returns the original data (basic cleanup only)
func (c *Chunk) FAQMetadata() (*FAQChunkMetadata, error) {
	if c == nil || len(c.Metadata) == 0 {
		return nil, nil
	}
	var meta FAQChunkMetadata
	if err := json.Unmarshal(c.Metadata, &meta); err != nil {
		return nil, err
	}
	meta.Sanitize() // Basic cleanup only, preserving the original content
	return &meta, nil
}

// SetFAQMetadata sets FAQ metadata on a Chunk
// Original data is stored in the DB; ContentHash is computed from normalized data
func (c *Chunk) SetFAQMetadata(meta *FAQChunkMetadata) error {
	if c == nil {
		return nil
	}
	if meta == nil {
		c.Metadata = nil
		c.ContentHash = ""
		return nil
	}
	// Stored in the DB after basic cleanup (original content preserved)
	meta.Sanitize()
	bytes, err := json.Marshal(meta)
	if err != nil {
		return err
	}
	c.Metadata = JSON(bytes)
	// ContentHash is computed from normalized data, used for dedup matching
	normalized := meta.Normalize()
	c.ContentHash = CalculateFAQContentHash(normalized)
	return nil
}

// CalculateFAQContentHash computes the hash value of FAQ content
// Hash is based on: standard question + similar questions (sorted) + counterexamples (sorted) + answers (sorted)
// Used for fast matching and deduplication
func CalculateFAQContentHash(meta *FAQChunkMetadata) string {
	if meta == nil {
		return ""
	}

	// Normalize() returns a new copy; the old code discarded the return value.
	normalized := meta.Normalize()
	if normalized == nil {
		return ""
	}

	// Sorts the array (ensures identical content produces identical hashes)
	similarQuestions := make([]string, len(normalized.SimilarQuestions))
	copy(similarQuestions, normalized.SimilarQuestions)
	sort.Strings(similarQuestions)

	negativeQuestions := make([]string, len(normalized.NegativeQuestions))
	copy(negativeQuestions, normalized.NegativeQuestions)
	sort.Strings(negativeQuestions)

	answers := make([]string, len(normalized.Answers))
	copy(answers, normalized.Answers)
	sort.Strings(answers)

	// Builds the string used for hashing: standard question + similar questions + counterexamples + answers
	var builder strings.Builder
	builder.WriteString(normalized.StandardQuestion)
	builder.WriteString("|")
	builder.WriteString(strings.Join(similarQuestions, ","))
	builder.WriteString("|")
	builder.WriteString(strings.Join(negativeQuestions, ","))
	builder.WriteString("|")
	builder.WriteString(strings.Join(answers, ","))

	// Computes the SHA256 hash
	hash := sha256.Sum256([]byte(builder.String()))
	return hex.EncodeToString(hash[:])
}

// AnswerStrategy defines the answer return strategy
type AnswerStrategy string

const (
	// AnswerStrategyAll returns all answers
	AnswerStrategyAll AnswerStrategy = "all"
	// AnswerStrategyRandom returns one answer at random
	AnswerStrategyRandom AnswerStrategy = "random"
)

// FAQEntry represents an FAQ entry returned to the frontend
type FAQEntry struct {
	ID                int64          `json:"id"`
	ChunkID           string         `json:"chunk_id"`
	KnowledgeID       string         `json:"knowledge_id"`
	KnowledgeBaseID   string         `json:"knowledge_base_id"`
	TagID             int64          `json:"tag_id"`
	TagName           string         `json:"tag_name"`
	IsEnabled         bool           `json:"is_enabled"`
	IsRecommended     bool           `json:"is_recommended"`
	StandardQuestion  string         `json:"standard_question"`
	SimilarQuestions  []string       `json:"similar_questions"`
	NegativeQuestions []string       `json:"negative_questions"`
	Answers           []string       `json:"answers"`
	AnswerStrategy    AnswerStrategy `json:"answer_strategy"`
	IndexMode         FAQIndexMode   `json:"index_mode"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CreatedAt         time.Time      `json:"created_at"`
	Score             float64        `json:"score,omitempty"`
	MatchType         MatchType      `json:"match_type,omitempty"`
	ChunkType         ChunkType      `json:"chunk_type"`
	// MatchedQuestion is the actual question text that was matched in FAQ search
	// Could be the standard question or one of the similar questions
	MatchedQuestion string `json:"matched_question,omitempty"`
}

// FAQExportEntry represents an FAQ entry for JSON export, compatible with FAQEntryPayload's import format,
// making the "export → edit → re-import" cycle easier. When adding new fields, always keep omitempty to avoid breaking
// compatibility with historical export files.
type FAQExportEntry struct {
	ID                int64          `json:"id"`
	TagName           string         `json:"tag_name,omitempty"`
	StandardQuestion  string         `json:"standard_question"`
	SimilarQuestions  []string       `json:"similar_questions,omitempty"`
	NegativeQuestions []string       `json:"negative_questions,omitempty"`
	Answers           []string       `json:"answers,omitempty"`
	AnswerStrategy    AnswerStrategy `json:"answer_strategy,omitempty"`
	IsEnabled         bool           `json:"is_enabled"`
	IsRecommended     bool           `json:"is_recommended"`
}

// FAQEntryPayload is the payload used to create/update an FAQ entry
type FAQEntryPayload struct {
	// ID optional; specify seq_id for data migration (must be less than the auto-increment start 100000000)
	ID                *int64          `json:"id,omitempty"`
	StandardQuestion  string          `json:"standard_question"    binding:"required"`
	SimilarQuestions  []string        `json:"similar_questions"`
	NegativeQuestions []string        `json:"negative_questions"`
	Answers           []string        `json:"answers"`
	AnswerStrategy    *AnswerStrategy `json:"answer_strategy,omitempty"`
	TagID             int64           `json:"tag_id"`
	TagName           string          `json:"tag_name"`
	IsEnabled         *bool           `json:"is_enabled,omitempty"`
	IsRecommended     *bool           `json:"is_recommended,omitempty"`
}

const (
	FAQBatchModeAppend  = "append"
	FAQBatchModeReplace = "replace"
)

// FAQBatchUpsertPayload batch-imports FAQ entries
type FAQBatchUpsertPayload struct {
	Entries     []FAQEntryPayload `json:"entries"      binding:"required"`
	Mode        string            `json:"mode"         binding:"oneof=append replace"`
	KnowledgeID string            `json:"knowledge_id"`
	TaskID      string            `json:"task_id"` // Optional; auto-generates a UUID if omitted
	DryRun      bool              `json:"dry_run"` // Validate only, does not actually import
}

// FAQFailedEntry represents an entry that failed import/validation
type FAQFailedEntry struct {
	Index             int      `json:"index"`                        // The entry's index within the batch (0-based)
	Reason            string   `json:"reason"`                       // Failure reason
	FailureType       string   `json:"failure_type,omitempty"`       // Failure type: pre_validation / post_validation
	IsPartialFailure  bool     `json:"is_partial_failure,omitempty"` // Whether this is a partial failure (similar questions/counterexamples were removed, but the entry can still be imported)
	TagName           string   `json:"tag_name,omitempty"`           // Category
	StandardQuestion  string   `json:"standard_question"`            // Standard question
	SimilarQuestions  []string `json:"similar_questions,omitempty"`  // Similar questions
	NegativeQuestions []string `json:"negative_questions,omitempty"` // Counterexample questions
	Answers           []string `json:"answers,omitempty"`            // Answer
	AnswerAll         bool     `json:"answer_all,omitempty"`         // Whether to reply to all
	IsDisabled        bool     `json:"is_disabled,omitempty"`        // Whether disabled
	// Partial failure details (when IsPartialFailure is true)
	RemovedSimilarQuestions  []string `json:"removed_similar_questions,omitempty"`  // Removed similar questions and reasons
	RemovedNegativeQuestions []string `json:"removed_negative_questions,omitempty"` // Removed counterexamples and reasons
}

// FAQMergeDetail represents a summary of the result of merging an FAQ with an existing chunk in append mode.
type FAQMergeDetail struct {
	Index            int    `json:"index"`              // Row number (index within the batch)
	StandardQuestion string `json:"standard_question"`  // Standard question
	AnswerChanged    bool   `json:"answer_changed"`     // Whether the answer changed
	NewSimilarCount  int    `json:"new_similar_count"`  // Number of new similar questions added
	NewNegativeCount int    `json:"new_negative_count"` // Number of new counterexamples added
}

// FAQSuccessEntry represents simple information about a successfully imported entry
type FAQSuccessEntry struct {
	Index            int    `json:"index"`              // Index of the entry within the batch (starting from 0)
	SeqID            int64  `json:"seq_id"`             // Sequence ID of the entry after import
	TagID            int64  `json:"tag_id,omitempty"`   // Category ID (seq_id)
	TagName          string `json:"tag_name,omitempty"` // Category name
	StandardQuestion string `json:"standard_question"`  // Standard question
}

// FAQDryRunResult represents the validation result of dry_run mode
type FAQDryRunResult struct {
	TaskID        string           `json:"task_id,omitempty"` // Async task ID (returned in async mode)
	Total         int              `json:"total"`             // Total number of entries
	SuccessCount  int              `json:"success_count"`     // Number of entries that passed validation
	FailedCount   int              `json:"failed_count"`      // Number of entries that failed validation
	FailedEntries []FAQFailedEntry `json:"failed_entries"`    // Failed entry details
}

// FAQSearchRequest FAQ search request parameters
type FAQSearchRequest struct {
	QueryText            string  `json:"query_text"             binding:"required"`
	VectorThreshold      float64 `json:"vector_threshold"`
	MatchCount           int     `json:"match_count"`
	FirstPriorityTagIDs  []int64 `json:"first_priority_tag_ids"`  // First-priority tag ID list; limits the hit scope and has the highest priority
	SecondPriorityTagIDs []int64 `json:"second_priority_tag_ids"` // Second-priority tag ID list; limits the hit scope, lower priority than the first
	OnlyRecommended      bool    `json:"only_recommended"`        // Whether to return only recommended entries
}

// UntaggedTagName is the canonical (English) display name for entries without a tag.
const UntaggedTagName = "Untagged"

// IsUntaggedTagName reports whether name represents the special "no tag" tag.
// It accepts the canonical English name plus legacy aliases ("未分类", "Uncategorized")
// so existing deployments keep working after the English-default rollout.
func IsUntaggedTagName(name string) bool {
	switch name {
	case "Untagged", "未分类", "Uncategorized", "Not categorized", "Sem categoria":
		return true
	default:
		return false
	}
}

// FAQEntryFieldsUpdate field update for a single FAQ entry
type FAQEntryFieldsUpdate struct {
	IsEnabled     *bool  `json:"is_enabled,omitempty"`
	IsRecommended *bool  `json:"is_recommended,omitempty"`
	TagID         *int64 `json:"tag_id,omitempty"`
	// More fields can be added later
}

// FAQEntryFieldsBatchUpdate request for batch updating FAQ entry fields
// Supports two modes:
// 1. Update by entry ID: use the ByID field
// 2. Update by Tag: use the ByTag field, applying the same update to all entries under that Tag
type FAQEntryFieldsBatchUpdate struct {
	// ByID updates by entry ID; key is the entry ID (seq_id)
	ByID map[int64]FAQEntryFieldsUpdate `json:"by_id,omitempty"`
	// ByTag batch updates by tag; key is the tag ID (seq_id)
	ByTag map[int64]FAQEntryFieldsUpdate `json:"by_tag,omitempty"`
	// ExcludeIDs lists IDs (seq_id) to exclude in ByTag operations
	ExcludeIDs []int64 `json:"exclude_ids,omitempty"`
}

// FAQImportTaskStatus import task status
type FAQImportTaskStatus string

const (
	// FAQImportStatusPending represents the pending status of the FAQ import task
	FAQImportStatusPending FAQImportTaskStatus = "pending"
	// FAQImportStatusProcessing represents the processing status of the FAQ import task
	FAQImportStatusProcessing FAQImportTaskStatus = "processing"
	// FAQImportStatusCompleted represents the completed status of the FAQ import task
	FAQImportStatusCompleted FAQImportTaskStatus = "completed"
	// FAQImportStatusFailed represents the failed status of the FAQ import task
	FAQImportStatusFailed FAQImportTaskStatus = "failed"
)

// FAQImportProgress represents the progress of an FAQ import task stored in Redis
// When Status is "completed", the result fields (SkippedCount, ImportMode, ImportedAt, DisplayStatus, ProcessingTime) are populated.
type FAQImportProgress struct {
	TaskID             string              `json:"task_id"`                        // UUID for the import task
	KBID               string              `json:"kb_id"`                          // Knowledge Base ID
	KnowledgeID        string              `json:"knowledge_id"`                   // FAQ Knowledge ID
	Status             FAQImportTaskStatus `json:"status"`                         // Task status
	Progress           int                 `json:"progress"`                       // 0-100 percentage
	Total              int                 `json:"total"`                          // Total entries to import
	Processed          int                 `json:"processed"`                      // Entries processed so far
	SuccessCount       int                 `json:"success_count"`                  // Number of fully successful entries (excluding partial success/partial failure)
	FailedCount        int                 `json:"failed_count"`                   // Number of failed entries
	PartialFailedCount int                 `json:"partial_failed_count,omitempty"` // Number of partially failed entries (similar questions/counterexamples removed)
	SkippedCount       int                 `json:"skipped_count,omitempty"`        // Number of skipped entries (e.g. duplicates)
	FailedEntries      []FAQFailedEntry    `json:"failed_entries,omitempty"`       // Failed entry details (returned directly when few)
	FailedEntriesURL   string              `json:"failed_entries_url,omitempty"`   // Failed entry CSV download URL (returned when many)
	SuccessEntries     []FAQSuccessEntry   `json:"success_entries,omitempty"`      // Simple information for successful entries (returned directly when few)
	ValidEntryIndices  []int               `json:"valid_entry_indices,omitempty"`  // Indices of entries that passed validation (used to skip validation on retry)
	MergeEntryIndices  []int               `json:"merge_entry_indices,omitempty"`  // Index of entries to merge (internal use, for skipping recognition on retry)
	MergedCount        int                 `json:"merged_count,omitempty"`         // Number of entries updated via merge
	AddedCount         int                 `json:"added_count,omitempty"`          // Number of newly added entries
	MergeDetails       []FAQMergeDetail    `json:"merge_details,omitempty"`        // Merge details
	Message            string              `json:"message"`                        // Status message
	Error              string              `json:"error"`                          // Error message if failed
	CreatedAt          int64               `json:"created_at"`                     // Task creation timestamp
	UpdatedAt          int64               `json:"updated_at"`                     // Last update timestamp
	DryRun             bool                `json:"dry_run,omitempty"`              // Whether dry run mode is enabled

	// Result fields (populated when Status == "completed")
	ImportMode     string    `json:"import_mode,omitempty"`     // Import mode: append or replace
	ImportedAt     time.Time `json:"imported_at,omitempty"`     // Import completion time
	DisplayStatus  string    `json:"display_status,omitempty"`  // Display status: open or close
	ProcessingTime int64     `json:"processing_time,omitempty"` // Processing time (milliseconds)
}

// FAQImportMetadata stores FAQ import task info in Knowledge.Metadata
// Deprecated: Use FAQImportProgress with Redis storage instead
type FAQImportMetadata struct {
	ImportProgress  int `json:"import_progress"` // 0-100
	ImportTotal     int `json:"import_total"`
	ImportProcessed int `json:"import_processed"`
}

// FAQImportResult stores statistical results after FAQ import completes
// This information is persisted and does not follow progress status; it is replaced on the next import
type FAQImportResult struct {
	// Import statistics
	TotalEntries       int `json:"total_entries"`        // Total number of entries
	SuccessCount       int `json:"success_count"`        // Number of fully successful entries (excludes partial success/partial failure)
	FailedCount        int `json:"failed_count"`         // Number of fully failed entries
	PartialFailedCount int `json:"partial_failed_count"` // Number of partially failed entries (similar questions/counterexamples removed but imported)
	SkippedCount       int `json:"skipped_count"`        // Number of skipped entries (e.g. duplicates)
	MergedCount        int `json:"merged_count"`         // Number of entries updated via merge
	AddedCount         int `json:"added_count"`          // Number of newly added entries

	// Import mode and time info
	ImportMode string    `json:"import_mode"` // Import mode: append or replace
	ImportedAt time.Time `json:"imported_at"` // Import completion time
	TaskID     string    `json:"task_id"`     // Import task ID

	// Failure detail URL (download link provided when there are many failed entries)
	FailedEntriesURL string `json:"failed_entries_url,omitempty"` // Failed entries CSV download URL

	// Display control
	DisplayStatus string `json:"display_status"` // Display status: open or close

	// Extra statistics
	ProcessingTime int64 `json:"processing_time"` // Processing time (milliseconds)
}

// ToJSON converts the metadata to JSON type.
func (m *FAQImportMetadata) ToJSON() (JSON, error) {
	if m == nil {
		return nil, nil
	}
	bytes, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	return JSON(bytes), nil
}

// ToJSON converts the import result to JSON type.
func (r *FAQImportResult) ToJSON() (JSON, error) {
	if r == nil {
		return nil, nil
	}
	bytes, err := json.Marshal(r)
	if err != nil {
		return nil, err
	}
	return JSON(bytes), nil
}

// ParseFAQImportMetadata parses FAQ import metadata from Knowledge.
func ParseFAQImportMetadata(k *Knowledge) (*FAQImportMetadata, error) {
	if k == nil || len(k.Metadata) == 0 {
		return nil, nil
	}
	var metadata FAQImportMetadata
	if err := json.Unmarshal(k.Metadata, &metadata); err != nil {
		return nil, err
	}
	return &metadata, nil
}

// normalizeQuestionStrings normalizes the question list
// Includes full-width to half-width conversion, trailing punctuation removal, whitespace collapsing, and deduplication
func normalizeQuestionStrings(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	dedup := make([]string, 0, len(values))
	seen := make(map[string]struct{}, len(values))
	for _, v := range values {
		normalized := NormalizeQuestion(v)
		if normalized == "" {
			continue
		}
		if _, exists := seen[normalized]; exists {
			continue
		}
		seen[normalized] = struct{}{}
		dedup = append(dedup, normalized)
	}
	if len(dedup) == 0 {
		return nil
	}
	return dedup
}

// multiSpaceRegex matches multiple consecutive whitespace characters
var multiSpaceRegex = regexp.MustCompile(`\s+`)

// urlRegex matches URLs
var urlRegex = regexp.MustCompile(`https?://[^\s]+`)

// URLNormMode defines the URL normalization mode
type URLNormMode int

const (
	// URLRemove removes the URL entirely
	URLRemove URLNormMode = iota
	// URLPlaceholder replaces it with the placeholder <URL>
	URLPlaceholder
	// URLKeepDomain keeps only the domain
	URLKeepDomain
	// URLKeepDomainAndPath keeps the domain and path
	URLKeepDomainAndPath
)

// NormalizeQuestion normalizes the question text to improve vector matching hit rate
// Processing order reference: query = convert_st(trim_url(query.lower().strip().strip("？。，；、：""！?.,;!:'\"")), 1)
// 1. Trim leading and trailing whitespace
// 2. Remove URLs
// 3. Convert to lowercase
// 4. Strip leading and trailing punctuation
// 5. Convert Traditional Chinese to Simplified
// 6. Convert full-width symbols to half-width
// 7. Smart space handling (remove spaces between Chinese characters, keep between English/numbers)
func NormalizeQuestion(q string) string {
	q = strings.TrimSpace(q)
	if q == "" {
		return ""
	}

	// 1. Remove URLs
	q = trimURL(q)

	// 2. Convert to lowercase (effective for English)
	q = strings.ToLower(q)

	// 3. Strip leading and trailing punctuation
	q = strings.Trim(q, `？。，；、：""！?.,;!:'""`)

	// 4. Convert Traditional Chinese to Simplified
	q = toSimplified(q)

	// 5. Convert full-width characters to half-width
	q = toHalfWidth(q)

	// 6. Smart space handling: remove spaces between Chinese characters, keep between English/numbers
	q = normalizeSpaces(q)

	return strings.TrimSpace(q)
}

// normalizeSpaces handles spaces intelligently
// Rules:
// - Remove extra spaces in Chinese context
// - Keep necessary spaces between English/numbers
// Examples:
// - "怎么 绑定 手机" → "怎么绑定手机"
// - "iphone 15 怎么 激活" → "iphone 15怎么激活"
func normalizeSpaces(s string) string {
	// First merge multiple consecutive spaces into a single space
	s = multiSpaceRegex.ReplaceAllString(s, " ")

	runes := []rune(s)
	if len(runes) == 0 {
		return ""
	}

	var builder strings.Builder
	builder.Grow(len(s))

	for i := 0; i < len(runes); i++ {
		r := runes[i]

		// If it's not a space, write it directly
		if r != ' ' {
			builder.WriteRune(r)
			continue
		}

		// Handle spaces: check surrounding characters to decide whether to keep them
		// Get the previous non-space character
		var prevRune rune
		if i > 0 {
			prevRune = runes[i-1]
		}

		// Get the next non-space character
		var nextRune rune
		for j := i + 1; j < len(runes); j++ {
			if runes[j] != ' ' {
				nextRune = runes[j]
				break
			}
		}

		// Only keep the space when both surrounding characters are English letters or digits
		// Otherwise (including Chinese) remove the space
		if isASCIIAlphaNum(prevRune) && isASCIIAlphaNum(nextRune) {
			builder.WriteRune(' ')
		}
		// Otherwise skip the space
	}

	return builder.String()
}

// isASCIIAlphaNum checks whether a character is an ASCII letter or digit
func isASCIIAlphaNum(r rune) bool {
	return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')
}

// trimURL removes URLs from the string (using the default URLRemove pattern)
func trimURL(s string) string {
	return NormalizeURL(s, URLRemove)
}

// NormalizeURL processes URLs in the text according to the specified pattern
func NormalizeURL(text string, mode URLNormMode) string {
	return urlRegex.ReplaceAllStringFunc(text, func(raw string) string {
		switch mode {
		case URLRemove:
			return ""
		case URLPlaceholder:
			return "<URL>"
		case URLKeepDomain:
			domain, _ := parseURL(raw)
			if domain != "" {
				return domain
			}
			return "<URL>"
		case URLKeepDomainAndPath:
			domain, path := parseURL(raw)
			if domain != "" {
				return domain + path
			}
			return "<URL>"
		default:
			return "<URL>"
		}
	})
}

// parseURL parses a URL and returns the domain and path
func parseURL(raw string) (domain, path string) {
	// Remove the protocol prefix
	u := raw
	if strings.HasPrefix(u, "https://") {
		u = u[8:]
	} else if strings.HasPrefix(u, "http://") {
		u = u[7:]
	}

	// Separate domain and path
	slashIdx := strings.Index(u, "/")
	if slashIdx == -1 {
		// No path, the whole thing is the domain (may include query parameters)
		queryIdx := strings.Index(u, "?")
		if queryIdx != -1 {
			domain = u[:queryIdx]
		} else {
			domain = u
		}
		return domain, ""
	}

	domain = u[:slashIdx]
	path = u[slashIdx:]

	// Remove query parameters and fragment
	if queryIdx := strings.Index(path, "?"); queryIdx != -1 {
		path = path[:queryIdx]
	}
	if fragIdx := strings.Index(path, "#"); fragIdx != -1 {
		path = path[:fragIdx]
	}

	return domain, path
}

// toSimplified converts Traditional Chinese to Simplified Chinese
func toSimplified(s string) string {
	return textconv.ToSimplified(s)
}

// toHalfWidth converts full-width characters to half-width characters
// Mainly handles: full-width spaces, full-width ASCII characters (including punctuation)
func toHalfWidth(s string) string {
	var builder strings.Builder
	builder.Grow(len(s))

	for _, r := range s {
		switch {
		// Full-width space -> half-width space
		case r == '\u3000':
			builder.WriteRune(' ')
		// Full-width ASCII characters (! to ~, range 0xFF01-0xFF5E) -> half-width (0x0021-0x007E)
		case r >= 0xFF01 && r <= 0xFF5E:
			builder.WriteRune(r - 0xFF01 + 0x21)
		// Other characters remain unchanged
		default:
			builder.WriteRune(r)
		}
	}

	return builder.String()
}

// NormalizeQueryText normalizes search query text
// Same processing logic as NormalizeQuestion, used to normalize query text during search
func NormalizeQueryText(q string) string {
	return NormalizeQuestion(q)
}

// IsChineseChar determines whether a character is Chinese
func IsChineseChar(r rune) bool {
	return unicode.Is(unicode.Han, r)
}
