#!/usr/bin/env bash
set -euo pipefail

#
# Local build + package the WeKnora macOS desktop app (.app)
#
# Usage:
#   ./scripts/package-mac-app.sh
# SKIP_FRONTEND=1 ./scripts/package-mac-app.sh  # skip frontend build
#

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${ROOT_DIR}"

APP_NAME="WeKnora Lite"
APP_BUNDLE="${APP_NAME}.app"
DIST_DIR="dist/${APP_BUNDLE}"

echo "=== WeKnora Mac App Packager ==="
echo "  Output: dist/${APP_BUNDLE}"
echo ""

# ── Step 1: Build frontend (if not skipped) ──
if [ "${SKIP_FRONTEND:-}" != "1" ]; then
    if [ -f frontend/package.json ]; then
        echo ">> Building frontend..."
        (cd frontend && npm ci --prefer-offline && npm run build)
        # The Lite backend serves the SPA from ./web (see internal/router serveFrontendStatic); consistent with package-lite.sh, web must be updated with dist
        echo ">> Sync frontend/dist -> web/"
        rm -rf web
        cp -r frontend/dist web
    else
        echo ">> No frontend/package.json found, skipping frontend build"
    fi
fi

if [ ! -f web/index.html ]; then
    echo "WARNING: web/index.html not found. The Lite desktop app will serve the frontend from Resources/web; please build the frontend fully first (don't use SKIP_FRONTEND), or manually: cp -r frontend/dist web"
fi

# ── Step 2: Build with Wails ──
echo ">> Building Wails Desktop App..."

# If the wails CLI tool is not installed, remind the user to install it
if ! command -v wails >/dev/null 2>&1; then
    echo "Wails CLI not found. Please install it first:"
    echo "go install github.com/wailsapp/wails/v2/cmd/wails@latest"
    exit 1
fi

# Package using Wails (dependency proxy issues must be handled first)
export GONOSUMDB="git.sr.ht/*"
export GOPROXY="https://goproxy.cn,direct"
export CGO_CFLAGS="-Wno-deprecated-declarations"
export CGO_LDFLAGS="-Wl,-no_warn_duplicate_libraries"
export EDITION=lite

# Both Milvus's and Qdrant's generated gRPC code register a descriptor named "common.proto", which conflicts within the same process.
# -ldflags -X conflictPolicy=warn only applies to the final link step; it cannot override the separate go subprocess Wails launches during "generate bindings".
# Official approach: see https://protobuf.dev/reference/go/faq#namespace-conflict
export GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn

# Get the version number and configure LDFLAGS
eval "$(./scripts/get_version.sh env)"
LDFLAGS="$(./scripts/get_version.sh ldflags) -X 'google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn'"

# Generate Wails bindings by default (for window.go.main.App.*, etc.); if -skipbindings is added, __WEKNORA_API_BASE__ must be injected in OnDomReady
(cd cmd/desktop && wails build -clean -tags "sqlite_fts5" -ldflags="$LDFLAGS" -o "${APP_NAME}")

# ── Step 3: Copy generated .app to dist ──
echo ">> Assembling package..."
mkdir -p dist
rm -rf "${DIST_DIR}"
cp -R "cmd/desktop/build/bin/${APP_BUNDLE}" "dist/"

# Bundle the config file and initial database migration script into the .app's internal resources
RESOURCES_DIR="${DIST_DIR}/Contents/Resources"
mkdir -p "${RESOURCES_DIR}/config"
mkdir -p "${RESOURCES_DIR}/migrations/sqlite"

if [ -f .env.lite.example ]; then
    cp .env.lite.example "${RESOURCES_DIR}/.env"
fi
if [ -d migrations/sqlite ]; then
    cp -r migrations/sqlite/* "${RESOURCES_DIR}/migrations/sqlite/"
fi
if [ -d config ]; then
    cp -r config/* "${RESOURCES_DIR}/config/"
fi
if [ -d web ]; then
    cp -r web "${RESOURCES_DIR}/"
fi

# Note: the binary generated by Wails build has its working directory set to the app's Contents/MacOS directory by default
# May need to adjust the code's config file path reading logic later on

echo ""
echo "=== Done ==="
echo "  App generated at: dist/${APP_BUNDLE}"
echo "  You can double click it to run!"
